### ISSUE TITLE
Is it possible to extend a candidate info in helm buffer?

### ISSUE THREAD

**Issue by dvzubarev** [jixiuf/helm-dired-history#2]
For example add a full path of a directory.
It is extremely useful for remote directories, that were accessed by tramp.
Their names are often identical to local ones, so there is no chance to distinguish between them. 
Full paths may not be searchable by default, but may be exposed as annotations like in helm-bookmarks.

**Comment by jixiuf** [comment]
how about show tramp file with a different face ?

**Comment by jixiuf** [comment]
https://github.com/emacs-helm/helm/issues/1570

**Comment by dvzubarev** [comment]
I didn't know about Ctrl-] shortcut
It does what I was looking for.
Thank you for your effort
