### ISSUE TITLE
How to show full path of directories when view dired history?

### ISSUE THREAD

**Issue by tddsg** [jixiuf/helm-dired-history#4]
Hi,

I'm using your helm-dired-history package and find out it is quite useful. Thank you for creating and maintaining it. However, I notice that when viewing the history, only names of directories are displayed, but not their full path. 

So, I would like to ask if it is possible to view full paths of the directories? 
Personally, I think that will make your package more useful.

Bests,
Trung.

**Comment by jixiuf** [comment]
try C-]
