### ISSUE TITLE
Dired history is cleared after quitting an Emacs session

### ISSUE THREAD

**Issue by tddsg** [jixiuf/helm-dired-history#5]
I'm using the `helm-dired-history` mode in Spacemacs and when quitting an Emacs session and start a new one, the history of the previous session is completely cleared. 

When calling `helm-dired-history-view`, Emacs reports that "No history record". 

Is this the default feature of `helm-dired-history` or my Emacs setting somehow clears all the history?
If it is the latter case, do you know how to maintain the history record list?

Thank you very much!

**Comment by jixiuf** [comment]
```
(require 'savehist)
(add-to-list 'savehist-additional-variables 'helm-dired-history-variable)
(savehist-mode 1)
(eval-after-load 'dired
  '(progn (require 'helm-dired-history)
          (define-key dired-mode-map "," 'helm-dired-history-view)))
```
did you init it like this ?

**Comment by tddsg** [comment]
Thanks for your response. My init file is more or less the same:

```
(require 'savehist)
(add-to-list 'savehist-additional-variables 'helm-dired-history-variable)
(savehist-mode 1)
(require 'helm-dired-history)
```

I just tried on another computer and the problem is still the same.

**Comment by jixiuf** [comment]
helm-dired-history save the dired history by savehist-mode 
check your config about savehist-mode make sure it is turned on 
```
(print savehist-mode)  ;;should print "t"
```
```
(print savehist-additional-variables)   ;make sure helm-dired-history-variable is in the list 

(print (length savehist-additional-variables))
(print kill-emacs-hook)                 ;make sure savehist-autosave is in list
;; and make sure when you terminal your emacs session  ,kill-emacs-hook is called

```
if you do not customize variable "savehist-file"
check "~/.emacs.d/history"
it should contains one line like this
```
(setq helm-dired-history-variable '("path1" "path2"))
```

**Comment by jixiuf** [comment]
backup you .emacs.d    and .emacs(if exists)
test it with this 
```
(require 'package)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(or (file-exists-p package-user-dir)
    (package-refresh-contents))
(package-initialize)
(package-install 'helm-core)
(package-install 'helm-dired-history)

(require 'savehist)
(add-to-list 'savehist-additional-variables 'helm-dired-history-variable)
(savehist-mode 1)
(require 'helm-dired-history)
(require 'dired)
(define-key dired-mode-map "," 'helm-dired-history-view)
```

**Comment by tddsg** [comment]
Thanks for your detail explanation. I found out that `savehist-additional-variables` doesn't contain the `helm-dired-history-variable`. 

I keep my init code in a layer of Spacemacs

```
(defun tddsg/init-helm-dired-history ()
  (require 'savehist)
  (add-to-list 'savehist-additional-variables 'helm-dired-history-variable)
  (savehist-mode 1)
  (require 'helm-dired-history))
```

It was when initializing the `helm-dired-history`, but after that, somehow the variable `savehist-additional-variables` is cleared or modified by Spacemacs and `helm-dired-history-variable` is gone.

So, I have to keep the code `(add-to-list 'savehist-additional-variables 'helm-dired-history-variable)` in another function, which will be loaded at last, to avoid to be modified. 

Thank you again for the great advice.

**Comment by jixiuf** [comment]
ok,I will close this.
