### ISSUE TITLE
Enable dired-do-copy and dired-do-rename to support accessing the list of history directory

### ISSUE THREAD

**Issue by tddsg** [jixiuf/helm-dired-history#6]
Hello again,

I just have an idea about integrating your dired history feature into commands like `dired-do-copy` and `dired-do-rename`. What I think of is that when user press `C` (copy) or `R` (rename) mode, it is excellent to have an option allowing users to select a directory from the history list. 

How do you think about it?

I don't know how difficult it is, so I just want to post the idea here for the case it may be helpful.

**Comment by jixiuf** [comment]
code updated .
have a try.
maybe there are some bug exists .

**Comment by tddsg** [comment]
Wow, that is wonderful. I will definitely try it out and inform you if there are any problems.
Thanks so much for the update! :-D
