### ISSUE TITLE
#6 conflicts with dired-dwim-target

### ISSUE THREAD

**Issue by dvzubarev** [jixiuf/helm-dired-history#7]
Hi,
I have in my config (setq dired-dwim-target t)
I have two dired windows open side by side.
And I try to copy a file from one dired window to another.

Before  #6, Dired could guess the right destination. After #6 there is only candidates from dired history.
I suppose, that #6 may be off by default or directories from dired-history may be combined with dwim candidate.

**Comment by jixiuf** [comment]
code updated should be fixed

**Comment by dvzubarev** [comment]
Thank you, It works!
