### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jgarte** [jixiuf/helm-dired-history#9]
Hi I'd like to package this for upstream [GNU Guix](guix.gnu.org) but the package would need a license for me to submit it.

I have a guix package here for helm-dired-history:

**Comment by jixiuf** [comment]
a LICENSE is added. 
Is that. ok for you?

**Comment by jgarte** [comment]
> a LICENSE is added. Is that. ok for you?

@jixiuf 

Sure, that works! thanks.

I added the package to [Guix 'R Us](https://git.sr.ht/~whereiseveryone/guixrus/tree/master/item/guixrus/packages/emacs.scm#L949) as a pre-release and I'll send a patch to [upstream](guix.gnu.org) later this week.
